oumi-ai/oumi

- notebooks/Oumi - Custom Judge.ipynb
- notebooks/Oumi - Deploying a Job.ipynb
- notebooks/Oumi - Distill a Large Model.ipynb
- notebooks/Oumi - Evaluation with AlpacaEval 2.0.ipynb
- notebooks/Oumi - Evaluation with MT Bench.ipynb
- notebooks/Oumi - Evaluation with Oumi.ipynb
- notebooks/Oumi - Finetuning Tutorial.ipynb
- notebooks/Oumi - Launching Jobs on Custom Clusters.ipynb
- notebooks/Oumi - Oumi Judge.ipynb
- notebooks/Oumi - Running Jobs Remotely.ipynb
- notebooks/Oumi - Training CNN on Custom Dataset.ipynb
- notebooks/Oumi - Using NanoGPT.ipynb
- notebooks/Oumi - Using vLLM Engine for Inference.ipynb
- notebooks/Oumi - Vision Language Models.ipynb
- Update notebook intros
Closes OPE-948
> Update notebook intros

- .gitignore
> [tiny] Add docs auto-generated `.rst` files to gitignore

- README.md
> [tiny] use GitHub link for header

- docs/user_guides/infer/common_workflows.md
- docs/user_guides/infer/configuration.md
- Update inference engines reference
> [docs][tiny] update inference engines reference

- src/oumi/builders/models.py
- tests/unit/builders/test_models.py
-- Update logging and unit tests related to chat templates 
Towards OPE-957
> Update logging and unit tests related to chat templates

- notebooks/Oumi - Vision Language Models.ipynb
> Add HF_TOKEN instructions to Oumi Multimodal notebook

- docs/resources/datasets/pretraining_datasets.md
stream and packing keys are duplicated in the example
> remove duplicate keys in config example

- notebooks/Oumi - Evaluation with MT Bench.ipynb
- notebooks/Oumi - Vision Language Models.ipynb
-- Add hardware requirements section
-- Add a note to restart notebook after the first `pip install` for the changes to take  effect. NOTE: I may replicate this notice in more notebooks after the initial review.
Towards OPE-911
> [Notebooks] Update VLM notebook

- src/oumi/builders/training.py
> Fix typo and update warning message for OUMI trainer

- notebooks/Oumi - Deploying a Job.ipynb
- notebooks/Oumi - Distill a Large Model.ipynb
- notebooks/Oumi - Finetuning Tutorial.ipynb
- notebooks/Oumi - Launching Jobs on Custom Clusters.ipynb
- notebooks/Oumi - Running Jobs Remotely.ipynb
- notebooks/Oumi - Training CNN on Custom Dataset.ipynb
- notebooks/Oumi - Using vLLM Engine for Inference.ipynb
-- Add a note that a notebook kernel restart may be needed after the first `pip install oumi`
> [Notebooks] Add a note that a notebook kernel restart may be needed after `pip install oumi`

- src/oumi/core/datasets/vision_language_dataset.py
- src/oumi/datasets/chat_templates/phi3-instruct.jinja
- tests/unit/builders/test_models.py
- tests/unit/datasets/test_chat_templates.py
-- Update `phi3-instruct` chat template to support multiple images
-- Add test to verify that Oumi's `phi3-instruct` template output is the same as for original built-in model template for text-only (can't do it for images as the original chat template is text-only)
-- Add test to verify the `phi3-instruct` output for multimodal conversation is as expected
-- Rename some vars in `vision_language_dataset.py` for clarify
Fixes OPE-575
> Update Phi3 to support multiple images

- notebooks/Oumi - A Tour.ipynb
-- Add a note to Tour notebook to restart kernel after the first `pip install` as in https://github.com/oumi-ai/oumi/pull/1318
https://github.com/oumi-ai/oumi/issues/1325
Towards OPE-981
> [Notebooks] Add a note to Tour notebook to restart kernel after the first `pip install`

- configs/recipes/llama3_1/inference/8b_sglang_infer.yaml
- configs/recipes/vision/llama3_2_vision/inference/11b_sglang_infer.yaml
-- The previous value `--mem-fraction-static=0.99` was selected to run Llama 3.2 Vision on GPU with 24GB (barely fits), and generally such a high limit is unsafe/not-recommended to use.  0.9 is more reasonable.
> Tweak `--mem-fraction-static` param in sample SGLang configs

- scripts/polaris/launcher.sh
> chore: update launcher.sh

- notebooks/Oumi - Training CNN on Custom Dataset.ipynb
- notebooks/Oumi - Vision Language Models.ipynb
> [Notebooks] Minor improvements  in VLM and CNN notebooks

- configs/recipes/vision/llava_7b/sft/oumi_gcp_job.yaml
- configs/recipes/vision/llava_7b/sft/trl_gcp_job.yaml
- configs/recipes/vision/phi3/sft/oumi_gcp_job.yaml
- configs/recipes/vision/phi3/sft/trl_gcp_job.yaml
- configs/recipes/vision/qwen2_vl_2b/evaluation/gcp_job.yaml
- configs/recipes/vision/qwen2_vl_2b/sft/gcp_job.yaml
- configs/recipes/vision/smolvlm/sft/gcp_job.yaml
- tests/scripts/launch_tests.sh
--Make them more unique to prevent conflicts when same name is used for clusters with different specs
> Update VLM cluster names in sample commands 

- README.md
- docs/index.md
I've added the badge from https://trendshift.io/repositories/12865 to both our README and docs main page.
Preview of our docs:
N/A
> Update our README and docs with the github trending badge.

- README.md
> Update README.md - Add DeepSeek to supported models

- docs/index.md
> Update index.md - Add DeepSeek to supported models

- README.md
-- Using the link created by "Create Status Badge" action  for GPU Tests workflow
> Update "GPU Tests" status badge in README page

- src/oumi/cli/env.py
- src/oumi/launcher/clients/sky_client.py
- src/oumi/utils/str_utils.py
- tests/unit/launcher/clients/test_sky_client.py
- tests/unit/utils/test_str_utils.py
-- If `OUMI_USE_SPOT_VM` is unspecified, empty, or set as "config"  then no-change : use the value from Job config
-- If `OUMI_USE_SPOT_VM` is set to `spot` or `preemptable` then launch SpotVM.
-- If `OUMI_USE_SPOT_VM` is set to `non-spot` or `non-preemptable` (dash and case are ignored) then launch non-SpotVM.
Fixes OPE-976
> Define `OUMI_USE_SPOT_VM` env var and start using it to override `use_spot` param 

- .github/ISSUE_TEMPLATE/bug-report.yaml
- .github/ISSUE_TEMPLATE/feature-request.yaml
> [nit] update default issue names

- README.md
- docs/index.md
Builds on #1340. Tested on both staging docs and README
N/A
> Have GitHub Trending image hyperlink to GitHub Trending page

- README.md
- docs/index.md
Linking to https://trendshift.io/repositories/12865, the source of the banner.
N/A
> Update the link for the trending banner.

- src/oumi/builders/models.py
-- Move code to disable caching in `model.config` to a helper function for reuse
-- Add an  additional snippet to also disable cache in `model.config.text_config`, which is often done for VLMs
Towards OPE-875
> Move code to disable caching in `model.config` to a helper function

- README.md
- docs/index.md
- notebooks/Oumi - A Tour.ipynb
- notebooks/Oumi - Custom Judge.ipynb
- notebooks/Oumi - Deploying a Job.ipynb
- notebooks/Oumi - Distill a Large Model.ipynb
- notebooks/Oumi - Evaluation with AlpacaEval 2.0.ipynb
- notebooks/Oumi - Evaluation with MT Bench.ipynb
- notebooks/Oumi - Evaluation with Oumi.ipynb
- notebooks/Oumi - Finetuning Tutorial.ipynb
- notebooks/Oumi - Launching Jobs on Custom Clusters.ipynb
- notebooks/Oumi - Oumi Judge.ipynb
- notebooks/Oumi - Running Jobs Remotely.ipynb
- notebooks/Oumi - Training CNN on Custom Dataset.ipynb
- notebooks/Oumi - Using NanoGPT.ipynb
- notebooks/Oumi - Using vLLM Engine for Inference.ipynb
- notebooks/Oumi - Vision Language Models.ipynb
- Add a link to open each notebook in Colab at the top. This is in case users encounter the notebook file in GitHub/VSCode as opposed to our docs.
- Add commands to install Oumi to notebooks missing it.
- Add instructions to add the HF token and sign the Llama agreement to notebooks missing it.
- For notebooks requiring GPUs to run on Colab, add a notice to switch to the T4 GPU runtime. Note that some notebooks don't need to do this, ex. for the Oumi launcher.
Future work:
- Test all notebooks to make sure they run on Colab. Some notebooks (ex. vLLM inference) will need modification to do so.
- [minor] Fix header sizes, which are inconsistent across notebooks
Towards OPE-1000
> Update notebooks to improve their Colab experience

- .github/ISSUE_TEMPLATE/bug-report.yaml
- .github/ISSUE_TEMPLATE/feature-request.yaml
Bugs and Feature Requests should be tagged with the appropriate types and labels.
Added the `triage` label to all newly logged issues.
N/A
> Add proper labels and types to new Bugs and Feature Requests.

- docs/faq/troubleshooting.md
Add several errors users have encountered on windows.
Installing in WSL resolves these issues.
Thanks for the reports in Discord!
N/A
> Update our FAQ for tips about installing oumi on Windows

- src/oumi/datasets/vision_language/__init__.py
- src/oumi/datasets/vision_language/docmatix.py
- src/oumi/datasets/vision_language/the_cauldron.py
- tests/integration/datasets/test_sft_vision_datasets_load_datasets.py
-- Add `DocmatixDataset` to  module's `__init__.py` file
-- Make `DocmatixDataset` a subclass of `TheCauldron` for code reuse since they share data format
-- Add `DocmatixDataset` to integration tests, and make them pass.
-- Allow multiple image and only include images in the first turn of multi-turn conversations. 
See also: https://github.com/oumi-ai/oumi/issues/916, https://github.com/oumi-ai/oumi/issues/915
Fixes OPE-748, OPE-747
Towards OPE-1021, OPE-355
> Cleanup `HuggingFaceM4/Docmatix` and `HuggingFaceM4/the_cauldron` multimodal datasets

- configs/recipes/vision/smolvlm/sft/gcp_job.yaml
-- No longer needed after  recent `transformers` upgrade
Fixes OPE-697
> Remove transformer version override for `HuggingFaceTB/SmolVLM-Instruct` in launcher script

- configs/recipes/vision/llava_7b/sft/train.yaml
- configs/recipes/vision/phi3/sft/train.yaml
- configs/recipes/vision/qwen2_vl_2b/sft/train.yaml
- configs/recipes/vision/smolvlm/sft/train.yaml
-- The use of the large dataset may require some extra infra work. Let's exclude it from examples for now.
-- Comments-only change
Towards OPE-1021
> Remove `Docmatix` dataset references from docstrings VLM config examples

- notebooks/Oumi - A Tour.ipynb
Fixed broken/incorrect link for "training" in introduction paragraph.
I removed an extra "h" in the "https" for the "training" link.
> Fixed broken link in Oumi - A Tour.ipynb notebook

- notebooks/Oumi - Custom Judge.ipynb
- notebooks/Oumi - Deploying a Job.ipynb
- notebooks/Oumi - Distill a Large Model.ipynb
- notebooks/Oumi - Evaluation with AlpacaEval 2.0.ipynb
- notebooks/Oumi - Evaluation with MT Bench.ipynb
- notebooks/Oumi - Evaluation with Oumi.ipynb
- notebooks/Oumi - Finetuning Tutorial.ipynb
- notebooks/Oumi - Launching Jobs on Custom Clusters.ipynb
- notebooks/Oumi - Oumi Judge.ipynb
- notebooks/Oumi - Running Jobs Remotely.ipynb
- notebooks/Oumi - Training CNN on Custom Dataset.ipynb
- notebooks/Oumi - Using NanoGPT.ipynb
- notebooks/Oumi - Using vLLM Engine for Inference.ipynb
- notebooks/Oumi - Vision Language Models.ipynb
Inspired by #1398, this PR fixes other `hhttp` typos.
N/A
> Fix broken links in notebooks.

- src/oumi/cli/env.py
- src/oumi/launcher/clients/slurm_client.py
- src/oumi/launcher/clouds/__init__.py
- src/oumi/launcher/clouds/slurm_cloud.py
- src/oumi/launcher/clusters/slurm_cluster.py
- tests/unit/launcher/clients/data/sacct_full.txt
- tests/unit/launcher/clients/test_slurm_client.py
- tests/unit/launcher/clouds/test_slurm_cloud.py
- tests/unit/launcher/clusters/test_slurm_cluster.py
This PR adds a cluster and cloud implementation for slurm.
In oumi, we'll consider a "cluster" a logical pair of a `hostname` and a `user`, ex `taenin@myslurmhost`.
This means that running jobs as a second user on the same host would be represented with a second cluster in oumi. Ex: `janedoe@myslurmhost`
Users can set the `OUMI_SLURM_CONNECTIONS` env var to automatically connect to specific slurm hosts in the oumi CLI. This should be a comma-separated list of <user>@<host> pairs.
Ex:
```
export OUMI_SLURM_CONNECTIONS="taenin@myslurmhost,janedoe@myslurmhost"
```
Fixes #1382
> Add a Slurm cluster and cloud to the oumi launcher.

- src/oumi/evaluation/lm_harness.py
Enabling our LM Harness integration to support a remote/local server.
Tested as follows:
1) Installed an LM Harness requirement locally
```
pip install lm-eval[api]
```
2) Launched a basic vLLM server:
```
python -m vllm.entrypoints.openai.api_server \
--model HuggingFaceTB/SmolLM2-135M-Instruct \
--port 6864
```
3) executed the following `YAML` code
```
model:
model_name: "HuggingFaceTB/SmolLM2-135M-Instruct"
model_max_length: 2048
torch_dtype_str: "bfloat16"
trust_remote_code: True
tasks:
- evaluation_platform: lm_harness
task_name: mmlu_college_computer_science
inference_engine: REMOTE
inference_remote_params:
api_url: "http://localhost:6864/v1/completions"
num_workers: 1
max_retries: 3
connection_timeout: 300
```
Towards OPE-1005
At least one review from a member of …
> [Evaluation] LM Harness remote server support

- configs/recipes/vision/llama3_2_vision/inference/11b_infer.yaml
- configs/recipes/vision/llama3_2_vision/inference/11b_rvllm_infer.yaml
- configs/recipes/vision/llama3_2_vision/inference/11b_sglang_infer.yaml
- configs/recipes/vision/llama3_2_vision/inference/11b_vllm_infer.yaml
- configs/recipes/vision/llava_7b/inference/infer.yaml
- configs/recipes/vision/llava_7b/inference/vllm_infer.yaml
- configs/recipes/vision/phi3/inference/vllm_infer.yaml
- configs/recipes/vision/qwen2_5_vl_3b/inference/infer.yaml
- configs/recipes/vision/qwen2_5_vl_3b/inference/vllm_infer.yaml
- configs/recipes/vision/qwen2_vl_2b/inference/infer.yaml
- configs/recipes/vision/qwen2_vl_2b/inference/sglang_infer.yaml
- configs/recipes/vision/qwen2_vl_2b/inference/vllm_infer.yaml
-- Include `--image` param, which is required to make these samples meaningful
> Update VLM sample `oumi infer -i` commands

- configs/recipes/llama3_1/inference/8b_sglang_infer.yaml
- configs/recipes/llama3_2/inference/1b_sglang_infer.yaml
- configs/recipes/llama3_2/inference/3b_sglang_infer.yaml
- configs/recipes/vision/llama3_2_vision/inference/11b_sglang_infer.yaml
- configs/recipes/vision/qwen2_vl_2b/inference/sglang_infer.yaml
-- Docker should be the recommended way to start SGLang, as Docker pulls pre-tested server configurations and avoids Python dependency conflicts.
-- Tested locally
Towards OPE-989
> Provide example show to start SGLang server using Docker

- src/oumi/inference/vllm_inference_engine.py
Set the local VLLM inference to use 90% of GPU vRAM.
100% usage causes OOMs when small amounts of vRAM are witheld.
N/A
> Set a better default for vllm inference GPU usage.

- src/oumi/cli/cli_utils.py
- src/oumi/cli/fetch.py
- src/oumi/cli/infer.py
- tests/unit/cli/test_cli_fetch.py
- tests/unit/cli/test_cli_infer.py
- tests/unit/cli/test_cli_utils.py
Make the config parameter required for oumi infer.
Also updated the `oumi fetch` default directory to `~/.oumi/fetch`. Updated tests accordingly.
Fixes #1442
> Require an inference config for oumi infer.

- scripts/benchmarks/minimal_multimodal_training.py
-- The dataset includes multi-image examples, good for testing this feature.
-- Add support for `--subset` param to the script.
> Add support for Docmatix dataset to multimodal training script

- src/oumi/core/configs/params/remote_params.py
- src/oumi/inference/remote_inference_engine.py
- tests/unit/core/configs/params/test_remote_params.py
- tests/unit/inference/test_remote_inference_engine.py
When using the RemoteInferenceEngine, you always want to supply an API URL. However, when using our wrapper engines such as the GeminiInferenceEngine, the base_url is already supplied.
Previously if I tried running `oumi infer` with additional remote_params such as `politeness_policy` or `num_workers` I'd receive an exception that the API URL is not provided.
This change allows setting these params while still respecting the base API URL.
N/A
> Update RemoteParams to no longer require an API URL.

- src/oumi/cli/cli_utils.py
- src/oumi/cli/fetch.py
- src/oumi/cli/infer.py
- tests/unit/cli/test_cli_fetch.py
- tests/unit/cli/test_cli_utils.py
I've slightly refactored the `oumi fetch` logic to live in `cli_utils` to make testing a bit easier.
I've also removed the `output_dir` argument from the `oumi infer` cli as it was unclear that it was for downloading configs. 
I also updated `oumi fetch` to fetch configs if the user omits the `oumi://` prefix.
Related to #1386
> Minor cleanup of oumi fetch

- src/oumi/utils/torch_utils.py
-- Use built-in param after migration to `pytorch 2.5`
Fixes OPE-644
> Remove a temp workaround in `pad_sequences` on the left side

- src/oumi/inference/gemini_inference_engine.py
- src/oumi/inference/remote_inference_engine.py
- tests/unit/inference/test_gemini_inference_engine.py
- tests/unit/inference/test_remote_inference_engine.py
If a user specifies an API endpoint that isn't the base endpoint (e.g. `https://api.openai.com/v1`) batch prediction will fail. Unfortunately, our wrapper engines like the OpenAIInferenceEngine specify paths of the form: `https://api.openai.com/v1/chat/completions`.
Additionally, not every engine supports batch requests (such as gemini). Updated the Gemini engine to simply return an error for `infer_batch`.
Fixes #1465
> Update the RemoteInferenceEngine to appropriately handle openai format batch prediction endpoints.

- configs/apis/anthropic/infer_claude3_7.yaml
Runnabled by anyone, anywhere, with the command:
`oumi infer -c oumi://configs/api/anthropic/infer_claude3_7.yaml -i`
> Create an inference config for Claude Sonnet 3.7

- configs/examples/grpo_tldr/gcp_job.yaml
- configs/examples/grpo_tldr/train.yaml
> Add sample DDP/GCP config for GRPO trainer

- configs/recipes/gpt2/evaluation/async_eval.yaml
> [tiny] Update async_eval.yaml comments to reference correct class

- configs/examples/grpo_tldr/gcp_job.yaml
- configs/examples/grpo_tldr/train.yaml
- pyproject.toml
- src/oumi/core/configs/__init__.py
- src/oumi/core/configs/params/grpo_params.py
- src/oumi/core/configs/params/training_params.py
-- Include initial set of params including  vLLM-related params.
-- Tested vLLM completions on 1 GPU.  Distributed  multi-GPU setup still needs work.
Towards OPE-993
> Define `GrpoParams` under configs

- src/oumi/cli/evaluate.py
- src/oumi/cli/judge.py
- src/oumi/cli/launch.py
- src/oumi/cli/train.py
- tests/unit/cli/test_cli_evaluate.py
- tests/unit/cli/test_cli_infer.py
- tests/unit/cli/test_cli_judge.py
- tests/unit/cli/test_cli_launch.py
- tests/unit/cli/test_cli_train.py
Each CLI entrypoint calls the ```cli_utils.fetch_and_resolve_config``` function before proceeding with the existing logic. This resolves the path if it includes ```oumi://``` prefix and otherwise returns the existing path unchanged.
Fixes #1444 
@taenin
> Updated all CLI endpoints to support oumi:// prefix

- src/oumi/core/models/base_model.py
The docstring for the forward method was malformed.
Before:
After:
N/A
> Update documentation formatting for BaseModel

- src/oumi/core/evaluation/backends/lm_harness.py
Fix issue where `log_samples` kwarg is not able to be passed to lm_harness
> Fix `log_samples` not propagating from `eval_kwargs`

- src/oumi/core/configs/params/evaluation_params.py
- src/oumi/core/evaluation/backends/alpaca_eval.py
- src/oumi/core/evaluation/backends/lm_harness.py
Adding support for logging model samples for all backends.
Generalizing Jeremy's PR-1496 for all backends
> [Evaluation] Adding support for logging model samples for all backends

- src/oumi/core/configs/params/evaluation_params.py
Support for deprecated input param (` evaluation_platform`) in order to not break any users that have taken a dependency on this. 
> Support for deprecated input param (` evaluation_platform`)

- .github/workflows/ci_tests.yaml
- .github/workflows/gpu_tests.yaml
- .github/workflows/nightly_tests.yaml
- .github/workflows/pretest.yaml
This PR adds a new `ci_tests` workflow that triggers both our CPU and GPU tests in parallel on the `main` branch.
Currently our test badges in our README reflect the latest tests run from pull requests. This means that problematic PRs will cause our tests to be listed as failing even when tests pass on `main`.
Follow up work:
- Update our badges to look for only tests run on the `main` branch.
N/A
> Add recurring tests to keep our test badges updated.

- README.md
After manually running our GPU tests, I've updated the test badge to use results only from the `main` branch.
You can preview the badge here: https://github.com/oumi-ai/oumi/actions/workflows/gpu_tests.yaml/badge.svg?branch=main
N/A
> Update the GPU Tests badge to use results from main

- src/oumi/core/distributed.py
- src/oumi/train.py
> Minor logging improvements

- configs/recipes/qwq/sft/lora_gcp_job.yaml
- configs/recipes/qwq/sft/lora_train.yaml
Copies the config from `configs/recipes/deepseek_r1/sft/distill_qwen_32b`, which is a reasoning model based on the same architecture (Qwen 2.5 32B).
Tested on GCP.
Towards #1408
> Add Qwen QwQ Lora config

- src/oumi/core/evaluation/backends/alpaca_eval.py
- src/oumi/core/evaluation/evaluator.py
- tests/unit/core/evaluation/test_backend_alpaca_eval.py
- tests/unit/core/evaluation/test_evaluator.py
Enable re-using the same inference engine across all tasks. 
**_Exception_**: In the case of LM Harness: We need to destroy the engine, since LM Harness uses its own inference engine; a 2nd engine will allocate unnecessary resources, potentially increasing the memory footprint. 
> Evaluation: Inference optimizations

- configs/recipes/vision/qwen2_5_vl_3b/sft/gcp_job.yaml
> Qwen2.5 VL: Replace "from source" install with `transformers>=0.49`

- configs/projects/aya/evaluation/eval.yaml
- configs/recipes/deepseek_r1/evaluation/distill_llama_70b/eval.yaml
- configs/recipes/deepseek_r1/evaluation/distill_llama_8b/eval.yaml
- configs/recipes/deepseek_r1/evaluation/distill_qwen_1_5b/eval.yaml
- configs/recipes/deepseek_r1/evaluation/distill_qwen_32b/eval.yaml
- configs/recipes/gpt2/evaluation/async_eval.yaml
- configs/recipes/llama3_1/evaluation/70b_eval.yaml
- configs/recipes/llama3_1/evaluation/8b_eval.yaml
- configs/recipes/llama3_2/evaluation/1b_eval.yaml
- configs/recipes/llama3_2/evaluation/3b_eval.yaml
- configs/recipes/llama3_3/evaluation/70b_eval.yaml
- configs/recipes/phi3/evaluation/eval.yaml
- configs/recipes/qwq/evaluation/eval.yaml
- configs/recipes/smollm/evaluation/135m/eval.yaml
- configs/recipes/smollm/evaluation/135m/leaderboards/huggingface_leaderboard_v1_eval.yaml
- configs/recipes/smollm/evaluation/135m/leaderboards/huggingface_leaderboard_v2_eval.yaml
- configs/recipes/smollm/evaluation/135m/quickstart_alpaca_v2_eval.yaml
- configs/recipes/smollm/evaluation/135m/quickstart_eval.yaml
- configs/recipes/vision/llama3_2_vision/evaluation/11b_eval.yaml
- configs/recipes/vision/qwen2_vl_2b/evaluation/eval.yaml
- src/experimental/configs/projects/zephyr/evaluation/eval.yaml
- src/oumi/core/configs/params/evaluation_params.py
- tests/unit/core/evaluation/test_save_utils.py
Renaming `evaluation_platform` → `evaluation_backend` for compatibility with PR-1484. Now that we released a new PyPI package (0.1.8) we can start using the new field name in our yaml files (ie., `evaluation_backend`) that is compatible with the latest release. 
> [Evaluation] Renaming `evaluation_platform` → `evaluation_backend`

- src/oumi/core/datasets/base_map_dataset.py
-- Use effective `dataset_name` value
-- Only print `dataset_name`/`dataset_path` if non-empty to reduce clutter.
> Minor logging improvements in `BaseMapDataset`

- scripts/examples/batch_inference/README.md
- scripts/examples/batch_inference/bulk_infer.py
- scripts/examples/batch_inference/infer.yaml
- scripts/examples/batch_inference/smollm_infer.yaml
Adding a script used in a recent walkthrough video for Oumi.
N/A
> Upload scripts used in a Weekly Walkthrough

- SECURITY.md
- Add security.md notice, based on [GitHub example](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file)
> [docs] add security.md

- src/oumi/core/datasets/vision_language_dataset.py
- src/oumi/utils/conversation_utils.py
- tests/unit/core/datasets/test_vision_language_dataset.py
- tests/unit/utils/test_conversation_utils.py
-- Using large number of images can lead to _much_ higher (model-dependent)  VRAM usage during training  and OOMs
-- Support `max_images` param in `VisionLanguageSftDataset`  to address this issue (a more elaborate solution may be needed, but it's a starting point)
-- Add a util to remove excessive images in `conversation_utils`
> Multimodal: Limit max number of images per Conversation

- configs/recipes/vision/qwen2_5_vl_3b/sft/train.yaml
- src/oumi/core/configs/training_config.py
-- Setup and validate params for `vision_language_sft` collator. The collator expects VLM SFT dataset to only produce one column: 'conversation_json' (JSON-encoded `Conversation`)! This PR auto-configures misc other params for  `vision_language_sft`
Towards OPE-355, OPE-1109
> Auto-populate and validate params specific to `vision_language_sft` collator in `TrainingConfig`

- src/oumi/cli/cli_utils.py
- src/oumi/cli/env.py
- src/oumi/cli/main.py
- tests/unit/cli/test_cli_env.py
- tests/unit/cli/test_cli_utils.py
This PR comes in two small parts:
- Updates the `oumi env` command to use rich formatting
- Updates our ASCII logo
See the screenshot below for the new experience:
vs old experience:
Towards OPE-306
> Update Oumi Env to use Rich formatting

- src/oumi/cli/launch.py
- src/oumi/launcher/clusters/sky_cluster.py
- tests/unit/cli/test_cli_launch.py
- tests/unit/launcher/clusters/test_sky_cluster.py
Updates the launch CLI to leverage Rich, similar to #1541
I also resolved a small bug where a "down" sky cluster would prevent `oumi launch status` from resolving completely.
Towards OPE-306
> Update oumi launch to use Rich formatting

- src/oumi/cli/evaluate.py
- tests/unit/cli/test_cli_evaluate.py
Update oumi evaluate to use Rich formatting.
We make a best-effort to parse the results of evaluation and visualize them in the CLI. See unit tests for how we handle non-standard metrics.
Towards OPE-306
> Update oumi evaluate to use rich formatting.

- src/oumi/cli/cli_utils.py
- src/oumi/cli/infer.py
- src/oumi/cli/judge.py
- src/oumi/cli/train.py
- All `print(...)` statements in the CLI have been replaced with an alternative from Rich.
- Added a loading spinner when importing python deps for train
Fixes OPE-306
> Update the CLI to replace all prints with Rich prints.

- .github/ISSUE_TEMPLATE/bug-report.yaml
After switching to Rich formatting, we should render the `oumi env` output in a shell block.
N/A
> Render the oumi env command as a shell block in bug reports.

- notebooks/Oumi - Evaluation with Oumi.ipynb
- src/oumi/core/evaluation/backends/alpaca_eval.py
- tests/unit/core/evaluation/test_backend_alpaca_eval.py
Modifying Alpaca Eval results format to be consistent with LM Harness
> [Evaluation] Modifying Alpaca Eval results format to be consistent with LM Harness

- src/oumi/core/feature_generators/vision_language_conversation_feature_generator.py
- src/oumi/core/types/conversation.py
--  Reduce code duplication in `vision_language_conversation_feature_generator.py`
-- Remove noisy type aliases in conversation.py
Towards OPE-991
> Misc no-op code cleanups

- scripts/examples/evaluation/README.md
- scripts/examples/evaluation/custom_evaluation.py
Upload the code used in the new weekly walkthrough (posting tomorrow).
N/A
> Add code used for the evaluation demo.

- notebooks/Oumi - A Tour.ipynb
- notebooks/Oumi - Build your own Custom Evaluation (Reliability Classifier).ipynb
- notebooks/Oumi - Custom Judge.ipynb
- notebooks/Oumi - Deploying a Job.ipynb
- notebooks/Oumi - Distill a Large Model.ipynb
- notebooks/Oumi - Evaluation with AlpacaEval 2.0.ipynb
- notebooks/Oumi - Evaluation with Oumi.ipynb
- notebooks/Oumi - Finetuning Tutorial.ipynb
- notebooks/Oumi - Launching Jobs on Custom Clusters.ipynb
- notebooks/Oumi - MiniMath-R1-1.5B.ipynb
- notebooks/Oumi - Oumi Judge.ipynb
- notebooks/Oumi - Running Jobs Remotely.ipynb
- notebooks/Oumi - Training CNN on Custom Dataset.ipynb
- notebooks/Oumi - Using NanoGPT.ipynb
- notebooks/Oumi - Using vLLM Engine for Inference.ipynb
- notebooks/Oumi - Vision Language Models.ipynb
This is a temporary workaround for #1554 while we investigate why `uv` is installing the incorrect pypi package.
Fixes #1554
> Remove UV install from notebooks as this breaks colab

- notebooks/Oumi - Build your own Custom Evaluation (Hallucination Classifier).ipynb
Updates in hallucination notebook (requested by Manos for clarity).
Fixes N/A
> [Evaluation] Updates in hallucination notebook

- src/oumi/utils/torch_utils.py
-- Convert `Parameters` tom lowercase  for some cases to make message look better.
-- No-op.
> Logging message update in `log_number_of_model_parameters`

- src/oumi/core/evaluation/evaluator.py
Bug: Multiple GPUs attempt to save in the same folder
Fixes OPE-1151
> [Evaluation] Bug: Multiple GPUs attempt to save in the same folder

- tests/scripts/gcp_e2e_tests_job.yaml
- tests/scripts/launch_tests.sh
-- Switch to `pip install -U ...` to run on latest versions.
-- Use detach  `oumi launch up ... --detach` to launch all 3 jobs in parallel
-- Drop `set -x` to reduce noisy command echoing.
Towards OPE-909
> Minor updates to e2e eternal tests scripts

- notebooks/Oumi - Build your own Custom Evaluation (Hallucination Classifier).ipynb
- src/oumi/core/evaluation/evaluation_result.py
- src/oumi/core/evaluation/evaluator.py
- tests/unit/core/evaluation/test_evaluator.py
Custom Evaluations: Simplifying custom evaluation function's output
Towards OPE-1097, OPE-1156
> [Evaluations][Custom] Simplify custom eval function output

- src/oumi/core/evaluation/evaluator.py
- tests/unit/core/evaluation/test_evaluator.py
Custom functions: support for 2 output types
> [Evaluation] Custom functions: support for 2 output types

- src/oumi/datasets/__init__.py
- src/oumi/datasets/sft/__init__.py
- src/oumi/datasets/sft/huggingface.py
- src/oumi/datasets/sft/oumi_conversation.py
Add support for conversational datasets from huggingface
> Add support for conversational datasets from huggingface

- src/oumi/datasets/sft/prompt_response.py
PromptResponseDataset: make model_output optional
Fixes N/A
> PromptResponseDataset: make model_output optional

- configs/recipes/deepseek_r1/evaluation/distill_llama_8b/eval.yaml
- configs/recipes/deepseek_r1/evaluation/distill_llama_8b/gcp_job.yaml
- configs/recipes/deepseek_r1/evaluation/distill_qwen_1_5b/eval.yaml
- configs/recipes/llama3_1/evaluation/8b_eval.yaml
- configs/recipes/llama3_1/evaluation/8b_gcp_job.yaml
- configs/recipes/llama3_1/evaluation/8b_polaris_job.yaml
- configs/recipes/phi3/evaluation/eval.yaml
- configs/recipes/phi3/evaluation/gcp_job.yaml
- configs/recipes/smollm/evaluation/135m/eval.yaml
- configs/recipes/vision/qwen2_5_vl_3b/sft/gcp_job.yaml
- pyproject.toml
- tests/e2e/test_eval_e2e.py
- tests/scripts/launch_tests.sh
-- Upgrade to `v4.49.*` , which is needed for Qwen 2.5 VL support
-- Updated more eval configs to use `shard_for_eval: True` for compatibility (see OPE-931), and for consistency with larger model sizes.
-- Upgrade to `v4.50` may be less straightforward (observed some errors/issues) to be handled later separately.
-- Tested: e2e integration tests` tests/scripts/launch_tests.sh` + some manual tests, including inference
Towards OPE-984, OPE-931, OPE-1175
> Upgrade `transformers` to `v4.49.*`

- src/oumi/core/evaluation/metrics.py
Support for confidence intervals
Fixes N/A
> [Evaluation] Support for confidence intervals

- configs/projects/halloumi/halloumi_eval_notebook.ipynb
> Halloumi notebook ruff formatting

- configs/projects/halloumi/8b_train.yaml
- configs/projects/halloumi/README.md
- configs/projects/halloumi/gcp_job.yaml
This adds additional useful information, and makes them consistent with our other config. By using the `oumi://` config prefix, users can run the config without cloning the repo.
Additionally, this replaces the table image with a markdown table.
> Update HallOumi configs

- docs/resources/datasets/datasets.md
> docs: update datasets.md

- tests/e2e/test_train_e2e.py
-- Tested OK with `A100:4`
Towards OPE-1122
> Enable letter_counting GRPO e2e integration test

- configs/projects/halloumi/README.md
[HallOumi Readme] Link to inference notebook
Fixes N/A
> [HallOumi Readme] Link to inference notebook

- configs/projects/halloumi/README.md
- configs/projects/halloumi/gcp_job.yaml
- Clean up HallOumi README
- Remove a script from the gcp job.
N/A
> Update HallOumi Readme and Job.

- configs/projects/halloumi/halloumi_eval_notebook.ipynb
HallOumi: Eval notebook - minor improvements
Fixes N/A
> [HallOumi] Evaluation notebook improvements

- README.md
Add a `news` section to our main readme.
> Add a news section to the readme

- configs/projects/halloumi/README.md
HallOumi README: Adding Clarity  - better differentiating between generative and classifier
Fixes N/A
> [HallOumi] README: Adding Clarity - differentiating between generative and classifier

- configs/recipes/llama4/evaluation/scout_instruct_eval.yaml
> [configs] Add llama4 eval configs

- src/oumi/cli/alias.py
- src/oumi/cli/evaluate.py
- src/oumi/cli/infer.py
- src/oumi/cli/launch.py
- src/oumi/cli/train.py
- tests/unit/cli/test_cli_alias.py
- tests/unit/cli/test_cli_evaluate.py
- tests/unit/cli/test_cli_infer.py
- tests/unit/cli/test_cli_launch.py
- tests/unit/cli/test_cli_train.py
This PR adds aliases to the CLI to work as shorthand for commonly used configs.
For example, the old command:
```
oumi train -c oumi://configs/recipes/llama4/sft/scout_base_full/train.yaml
```
can now be shortened to
```
oumi train -c llama4-scout
```
N/A
> Add alias functionality for train, launch, evaluate, and infer in the oumi CLI

- configs/recipes/llama4/sft/scout_base_full/gcp_job.yaml
- configs/recipes/llama4/sft/scout_instruct_full/gcp_job.yaml
Add the `oumi://` prefix to the llama4 GCP configs to ensure the path exists when running from a non-dev environment.
N/A
> Update llama4 GCP jobs for non-dev environments.

- src/oumi/core/configs/params/generation_params.py
- src/oumi/core/configs/params/remote_params.py
- src/oumi/inference/anthropic_inference_engine.py
- src/oumi/inference/gcp_inference_engine.py
- src/oumi/inference/gemini_inference_engine.py
- src/oumi/inference/openai_inference_engine.py
- src/oumi/inference/remote_inference_engine.py
- tests/unit/inference/test_anthropic_inference_engine.py
- tests/unit/inference/test_gcp_inference_engine.py
- tests/unit/inference/test_gemini_inference_engine.py
- tests/unit/inference/test_generation_params.py
- tests/unit/inference/test_openai_inference_engine.py
Remote Inference: Update Defaults
**_Generation_**
- max_new_tokens: 256 -> 1024
- temperature: 0.0 -> 1.0 (_only for OpenAi o1_)
**_Remote Inference_**
- connection_timeout: 20 -> 300
- (num_workers, politeness_policy): (1,0) -->
- Anthropic (5,60)
- GCP (10,60)
- Gemini (2,60)
- OpenAI (50,60)
Fixes N/A
> [Remote Inference] Update Default Params

- pyproject.toml
It claims to make GRPO 6x faster: [github](https://github.com/huggingface/trl/releases/tag/v0.16.0). Tested all e2e tests
Fixes OPE-1157
> Update trl to 0.16

- src/oumi/builders/processors.py
- src/oumi/core/configs/params/model_params.py
- src/oumi/core/evaluation/backends/lm_harness.py
- src/oumi/core/feature_generators/vision_language_conversation_feature_generator.py
- src/oumi/inference/native_text_inference_engine.py
- src/oumi/inference/sglang_inference_engine.py
- src/oumi/train.py
- tests/unit/builders/test_processors.py
- tests/unit/core/configs/params/test_model_params.py
- tests/unit/core/evaluation/test_backend_lm_harness.py
-- Update `ModelParams` to include `processor_args`
-- Update `build_processor()` and most of its invocations,  except `vision_language_conversation_feature_generator.py`, which will be handled as a follow-up (it's a more involved change)
Towards OPE-1185
> Support custom `processor args` in `ModelParams`

- configs/examples/berry_bench/evaluation/eval.yaml
- configs/examples/berry_bench/evaluation/gcp_job.yaml
- notebooks/Oumi - Train a Letter Counting Model using GRPO.ipynb
- src/oumi/cli/evaluate.py
- src/oumi/datasets/grpo/__init__.py
- src/oumi/datasets/grpo/berry_bench.py
- src/oumi/evaluation/registry/__init__.py
- src/oumi/evaluation/registry/berry_bench_task.py
- src/oumi/evaluation/registry/count_letters_task.py
This is fairly similar to letter counting eval. We use a different answer format, to align with what most LLMs tend to output for JSON. Tested with Llama 3b (1/10 correct) and Anthropic (8/10 correct).
Towards OPE-1122
> Support BerryBench evaluation

- src/oumi/inference/remote_inference_engine.py
- tests/unit/inference/test_remote_inference_engine.py
Changes
- Do NOT include the AUTH BEARER header in the request, if API KEY is NOT available
- Fast fail if the API KEY is NOT available but required (`api_key_env_varname` is set)
Fixes N/A
> [Remote Inference] Error checking for `api_key`

- notebooks/Oumi - Training CNN on Custom Dataset.ipynb
This is so the output directory is properly tracked by the gitignore
> Rename cnn_mnist_example to cnn_mnist_tutorial

- scripts/demo.py
- fix build errors, accidentally caused by #1647 
> [bug] fix build errors

- src/oumi/cli/main.py
- Update CLI to use `-h` in addition to `--help`
Fixes OPE-757
> [tiny] Update cli help shorthand

- pyproject.toml
- src/oumi/core/trainers/verl_grpo_trainer.py
The VerlGRPO trainer is using a dependency that is not in our pyproject.toml. This causes runtime failures in environments that don't have ray installed.
N/A
> Fix a missing dependency in the verl trainer.

- README.md
- configs/recipes/qwen3/README.md
- configs/recipes/qwen3/evaluation/30b_a3b_eval.yaml
- configs/recipes/qwen3/evaluation/30b_a3b_gcp_job.yaml
- configs/recipes/qwen3/inference/30b_a3b_infer.yaml
- configs/recipes/qwen3/sft/30b_a3b_lora/gcp_job.yaml
- configs/recipes/qwen3/sft/30b_a3b_lora/train.yaml
- src/oumi/cli/alias.py
- tests/e2e/test_train_e2e.py
Similar to #1661, and additionally added an e2e to test multi-GPu training of an MoE model (a configuration we don't have yet). Tested that they all work.
Towards OPE-1209
> Add Qwen3 30B A3B configs

- src/oumi/builders/collators.py
- src/oumi/core/configs/params/training_params.py
- tests/unit/builders/test_collators.py
-- Provide a param to override `label_ignore_index` as requested by a user in https://github.com/oumi-ai/oumi/issues/1660
Fixes OPE-1208
> Provide option to configure `label_ignore_index` in training config

- docs/user_guides/evaluate/custom_evals.md
- docs/user_guides/evaluate/evaluate.md
Documentation: Custom Evaluations (1 of 2)
Note: This only adds the page for custom evaluations. I also need to update other parts of the evaluation documentation to properly link to this & introduce custom evals (in the overview section and wherever else is applicable).
Fixes N/A
> [Documentation] Custom Evaluations (PR 1-of-2)

- .github/workflows/doctests.yaml
- .github/workflows/gpu_tests.yaml
- .github/workflows/pretest.yaml
This PR sets the permissions for our workflows so they don't inherit from the default org permission set. This should ultimately be a no-op for the workflows as they all require only `read` permissions.
N/A
> Set explicit permissions for our test workflows.

- src/oumi/core/configs/params/grpo_params.py
Fixed by running
```
pre-commit run --all-files
```
Failed run: https://github.com/oumi-ai/oumi/actions/runs/14849096322/job/41689217638
N/A
> Fix broken tests due to precommit violations

- tests/scripts/e2e_tests_job.yaml
- tests/scripts/launch_tests.sh
Update our e2e tests to use GCP by default.
N/A
> Switch back to using GCP for e2e tests.

- tests/e2e/test_train_e2e.py
Currently our e2e test `test_train_multimodal_lora_1gpu_40gb` is broken. Upon inspection, the output looks fine. However, the test is failing because it's looking for a `config.json` in what is actually a LoRA training job. The root cause is that the test is mislabeled. Adding `is_lora` should resolve the issue.
(edit): Fixed another test with the same issue.
N/A
> Mark an e2e test as is_lora

- pyproject.toml
Click published a new version today with a breaking change: https://pypi.org/project/click/8.2.0/
Typer doesn't pin their Click version, and has an outstanding PR to fix this issue: https://github.com/fastapi/typer/pull/1145
This is a temporary change to prevent breakage in Oumi until Typer has updated their code accordingly.
N/A
> Fix a test breakage caused by a new Click version (8.2.0)

- README.md
> chore: edited the link to the stars badge

- pyproject.toml
-- The `transformers` library depends on `torchao` and I was getting errors when old/incompatible `torchao` version is installed: 
```
from ...modeling_utils import PreTrainedModel
File "/home/user/miniconda3/envs/oumi/lib/python3.11/site-packages/transformers/modeling_utils.py", line 53, in <module>
from torchao.quantization import Int4WeightOnlyConfig
ImportError: cannot import name 'Int4WeightOnlyConfig' from 'torchao.quantization' (/home/user/miniconda3/envs/oumi/lib/python3.11/site-packages/torchao/quantization/__init__.py)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/home/user/miniconda3/envs/oumi/bin/oumi", line 8, in <module>
sys.exit(run())
```
-- Configuring `torchao` version explicitly for better determinism …
> Add `torchao` version to `pyproject.toml`

- configs/examples/letter_counting/grpo/train.yaml
- src/oumi/core/configs/params/grpo_params.py
- src/oumi/datasets/grpo/rewards/count_letters_rewards.py
- tests/unit/datasets/grpo/rewards/test_count_letters_rewards.py
Updates letter counting reward function and hparams for better stability during training
N/A
> Update GRPO letter counting reward function and hparams for stability

- src/oumi/datasets/__init__.py
- src/oumi/datasets/sft/__init__.py
- src/oumi/datasets/sft/coalm.py
> Add CoALM dataset class

- configs/recipes/vision/smolvlm/inference/infer.yaml
- configs/recipes/vision/smolvlm/inference/vllm_infer.yaml
-- Add vLLM and HF inference configs for `HuggingFaceTB/SmolVLM-Instruct`
-- Docs will be updated separately
Fixes OPE-697
> Add sample inference configs for `HuggingFaceTB/SmolVLM-Instruct`

- tests/unit/core/test_distributed.py
- Minor update to fix the failing pre-commit checks
> [tiny] Minor update to fix the failing pre-commit checks

- docs/resources/datasets/vl_sft_datasets.md
- docs/user_guides/train/configuration.md
- docs/user_guides/train/training_methods.md
- src/oumi/builders/collators.py
- src/oumi/core/configs/params/data_params.py
- tests/unit/builders/test_collators.py
- Add collator kwargs field to DataParams
- This allows to customize the behavior of the collators via config
- This is required for some models that need specific hypeparameters (e.g. Molmo with process_individually)
> Add collator kwargs field to DataParams

- docs/development/dev_setup.md
The repo should be cloned first before being able to run the "make install-miniconda"
> Update dev_setup.md to correct the order of steps

- configs/recipes/vision/molmo/README.md
- configs/recipes/vision/molmo/sft/full/train.yaml
- src/oumi/core/configs/internal/supported_models.py
- src/oumi/core/processors/default_processor.py
- src/oumi/datasets/chat_templates/molmo.jinja
- Add configs for molmo support (internal config, chat template, train config)
- Add more documentation to the internal config code
> Add configs for molmo support

- src/oumi/core/evaluation/backends/alpaca_eval.py
- `alpaca_eval` is an optional dependency, and if not installed users will get a type check error
- This PR adds the proper type ignore to mitigate the issue (not the most elegant fix, open to suggestions)
> [tiny] fix pre-commits checks on a fresh install

- configs/recipes/vision/molmo/README.md
- configs/recipes/vision/molmo/sft/molmo_d_full/train.yaml
- configs/recipes/vision/molmo/sft/molmo_o_full/train.yaml
- Add config for the Molmo O variant
- Update readme to include both models
> Add config for the Molmo O variant

- configs/recipes/vision/molmo/grpo/train.yaml
- src/oumi/cli/alias.py
- Add experimental molmo grpo config
> Add experimental molmo grpo config and train aliases

- configs/recipes/vision/phi3/sft/full/completions_only_train.yaml
- src/oumi/core/collators/vision_language_sft_collator.py
- src/oumi/core/feature_generators/vision_language_conversation_feature_generator.py
- In individual process mode, the collator should drop/keep the leading feature as indicated by the internal config
- Handle edge case where the tensor to be masked is of size 1
> [tiny] fix bug with vl collator 

- src/oumi/core/configs/params/synthesis_params.py
- src/oumi/core/configs/synthesis_config.py
- tests/unit/core/configs/params/test_synthesis_params.py
- tests/unit/core/configs/test_synthesis_config.py
Add initial skeleton for data synthesis configs & params
Fixes OPE-1288
Fixes OPE-1290
> Add data synthesis config, params, and unit tests

- src/oumi/inference/remote_inference_engine.py
- src/oumi/utils/http.py
- tests/unit/inference/test_remote_inference_engine.py
- tests/unit/utils/test_http.py
Different inference APIs have different methods of producing errors, so in an effort to make our inference more robust, this PR attempts to increase coverage of possible error types.
In addition, I add support for fast failing on non-retryable error codes.
Towards OPE-1307
> Add support for additional exception types for remote inference engine, as well as fast failing for non-retryable status codes.

- configs/recipes/falcon_e/README.md
- configs/recipes/falcon_h1/README.md
Added a readme for the Falcon-E recipes. Added a note on how to set up dependencies for Falcon-{H1, E} to get it working locally
> Readme for Falcon-E and note on extra dependencies required

- src/oumi/utils/git_utils.py
- `git` cmd is used to log the git commit id.
- If `git` is not installed, the exception is `FileNotFoundError`
- Since reporting the commit id is best effort, this PR extends the exceptions list to add `FileNotFoundError`
> [tiny][bug] make git cmd optional

- configs/recipes/vision/phi3/sft/full/completions_only_train.yaml
- configs/recipes/vision/phi3/sft/full/train.yaml
-  Update phi3-vision configs to use oumi trainer
- Temporary workaround until this is is fixed:
- https://github.com/huggingface/transformers/issues/34690
- https://github.com/microsoft/PhiCookBook/issues/223
> [tiny] Update phi3-vision configs to use oumi trainer

- docs/development/dev_setup.md
mention that the results can be seen on the wandb website and to tear down the cluster when finished
> Update dev_setup.md to add additional instructions

- src/oumi/core/trainers/hf_trainer.py
- [bug] update trainer to save processor when training with fsdp
> [bug] update trainer to save processor when training with fsdp

- .github/workflows/release_docker.yaml
- Dockerfile
> Add docker release workflow

- src/oumi/core/distributed.py
- tests/unit/core/test_distributed.py
- Some environments set `RANK` / `LOCAL_RANK` to "", or "-1". Update `get_distributed_info` to treat those values as `0`
> [bug] fix rank/local rank parsing for docker env

- configs/projects/dcvlr/README.md
> [docs] update dcvlr readme

- Dockerfile
- We need to allow prerelease as we rely on an experimental version of omegaconf
> [bugfix] Allow prerelease when building docker image

- tests/integration/evaluate/test_evaluate_lm_harness.py
> [Evaluation] Disabling flaky MMMU test

- README.md
Adding to README relevant news from the past two months
> Updates to Oumi news for May, June

- tests/unit/inference/test_vllm_inference_engine.py
Fixes a breakage in pyright. See https://github.com/oumi-ai/oumi/actions/runs/15890125014
Fixes N/A
> Fix a pyright regression

- src/oumi/core/configs/judge_config_v2.py
Minor Fix: judge config being loaded from repo path
Towards OPE-1327
> Judge API V2 | Fix judge config from repo path

- CONTRIBUTING.md
Minor update to CONTRIBUTING.md
> Update our contributing guidelines.

- src/oumi/core/configs/params/synthesis_params.py
- src/oumi/core/synthesis/dataset_ingestion.py
- src/oumi/core/synthesis/planner.py
- tests/unit/core/synthesis/test_dataset_ingestion.py
- tests/unit/core/synthesis/test_planner.py
Synthesis may want to utilize pre-existing datasets in order to use their attributes as seed data for creating new datasets (think few-shot examples, sample metadata, or simply modifying existing datasets).
This PR adds support for loading datasets in a variety of formats and integrating them into the dataset planning process.
Fixes OPE-1289
> Add support for ingesting datasets for synthesis

- README.md
Notice for our July 24 webinar at top of README
Updated news items for June-July
> Webinar announcement and other news

- src/oumi/core/trainers/oumi_trainer.py
- src/oumi/utils/serialization_utils.py
- tests/unit/utils/test_serialization_utils.py
- Update oumi trainer to log paramters to supported platforms
- mlflow: only supports flat dicts, so we flatten the full config
- wandb: supports nested dicts, but using the same flattened dict as mlflow for consistency
- tensorboard: does not support param logging, so logging it as text
- Tested with training/eval/infer configs on all 3 platforms
> Add parameter logging to oumi trainer

- src/oumi/utils/logging.py
- Our CLI needs a refresh visually. One of the lowest effort improvements is to enable the rich logging handler
- This is currently experimental, and disabled by default
- Users can enable it by setting `export OUMI_ENABLE_RICH_LOGGING="1"`
- When oumi's log level is set to `DEBUG`, we additionally log a lot more information (more detailed stack traces, locals, etc)
> Add experimental option to use the rich logging handler

- docs/user_guides/train/configuration.md
- src/oumi/core/configs/params/grpo_params.py
Removed vllm_max_model_len and vllm_dtype as GRPOConfig from TRL no longer support it. 
> Remove deprecated grpo params

- src/oumi/core/configs/__init__.py
- src/oumi/core/configs/analyze_config.py
This is the first PR in a series of smaller, reviewable pull requests that break down the larger analyze functionality. The complete changes can be found in the full feature branch: [main...ryan-arman-anlyze_v0](https://github.com/oumi-ai/oumi/compare/main...ryan-arman-anlyze_v0)
This PR introduces the foundational configuration classes needed for the dataset analysis functionality.
Changes:
Added: src/oumi/core/configs/analyze_config.py
- DatasetAnalyzeConfig - Main configuration class for dataset analysis
- SampleAnalyzeConfig - Configuration for individual analyzer plugins
Updated: src/oumi/core/configs/__init__.py
- Added imports for the new config classes
- Added exports to __all__ list for public API
At least one review from a member of `oumi-ai/oumi-staff` is …
> feat: add analyze config classes and exports

- configs/recipes/qwen3/README.md
- configs/recipes/qwen3/evaluation/0.6b_eval.yaml
- configs/recipes/qwen3/evaluation/0.6b_gcp_job.yaml
- configs/recipes/qwen3/evaluation/1.7b_eval.yaml
- configs/recipes/qwen3/evaluation/1.7b_gcp_job.yaml
- configs/recipes/qwen3/evaluation/14b_eval.yaml
- configs/recipes/qwen3/evaluation/14b_gcp_job.yaml
- configs/recipes/qwen3/evaluation/4b_eval.yaml
- configs/recipes/qwen3/evaluation/4b_gcp_job.yaml
- configs/recipes/qwen3/evaluation/8b_eval.yaml
- configs/recipes/qwen3/evaluation/8b_gcp_job.yaml
- configs/recipes/qwen3/inference/0.6b_infer.yaml
- configs/recipes/qwen3/inference/1.7b_infer.yaml
- configs/recipes/qwen3/inference/14b_infer.yaml
- configs/recipes/qwen3/inference/4b_infer.yaml
- configs/recipes/qwen3/inference/8b_infer.yaml
- configs/recipes/qwen3/sft/0.6b_full/gcp_job.yaml
- configs/recipes/qwen3/sft/0.6b_full/train.yaml
- configs/recipes/qwen3/sft/1.7b_full/gcp_job.yaml
- configs/recipes/qwen3/sft/1.7b_full/train.yaml
- configs/recipes/qwen3/sft/14b_lora/gcp_job.yaml
- configs/recipes/qwen3/sft/14b_lora/train.yaml
- configs/recipes/qwen3/sft/4b_full/gcp_job.yaml
- configs/recipes/qwen3/sft/4b_full/train.yaml
- configs/recipes/qwen3/sft/8b_full/gcp_job.yaml
- configs/recipes/qwen3/sft/8b_full/train.yaml
Added more Qwen3 recipes for training, evaluation, and inference
Fixes OPE-1346
> Added more Qwen3 recipes for training, evaluation, and inference

- tests/unit/utils/test_analysis_utils.py
* Refactoring all tests to use a flat, function-based structure
* Introducing pytest fixtures for common mock setup
Towards OPE-1407
> Refactor test_analysis_utils.py to use fixtures and flat test structure

- src/oumi/cli/evaluate.py
- src/oumi/cli/infer.py
- src/oumi/core/configs/base_config.py
This PR adds configuration printing at the start of evaluation and
inference operations to help users verify that their CLI config overrides
are properly applied.
https://github.com/oumi-ai/oumi/issues/1629
Added a print method in the config class 
> added a baseline print method in config

- src/oumi/core/configs/quantization_config.py
- src/oumi/quantize/__init__.py
- src/oumi/quantize/constants.py
Add quantization configs. 
Towards OPE-1425
> add quantization config (part 1)

- src/oumi/core/synthesis/document_ingestion.py
Add a pyright exemption for an optional synthesis import.
> Fix a pyright error for synthesis

- src/oumi/__init__.py
- src/oumi/cli/alias.py
- src/oumi/cli/main.py
- src/oumi/cli/quantize.py
- src/oumi/quantize/__init__.py
cli integration
Towards: OPE-1425
> [Quantization] CLI integration (part 4)

- src/oumi/utils/verl_model_merger.py
- New syntax (using | ) is only support in python 3.10+
- Switch to using `Union` to unblock 3.9 support
> [tiny] update type annotations for python3.9 support

- tests/unit/cli/test_cli_launch.py
This PR fixes broken tests for python 3.10, as well as adding missing tests for https://github.com/oumi-ai/oumi/pull/1761
#1761 
> Fix broken launcher tests for python 3.10

- tests/unit/performance/test_torch_profiler_utils.py
> [tiny] skip torch profiler test with known issue

- src/oumi/cli/judge.py
- src/oumi/cli/main.py
- src/oumi/judge.py
- tests/integration/cli/test_judge_e2e.py
Adding support for judging `list(Conversation)` in CLI (only for generic judges)
Towards OPE-1327
> Judge API V2 | CLI support for Conversations

- README.md
Remove links to July webinar signup page, and add link to YouTube recording
> remove webinar ad, add webinar recording link

- configs/projects/judges/generic/safety.yaml
- docs/user_guides/judge/built_in_judges.md
- src/oumi/cli/alias.py
Adding a (generic) safety judge, inspired by the judge V1 prompt (but expanded to cover more cases)
Towards OPE-1327
> Judge API V2 | Add a safety judge

- src/oumi/utils/logging.py
- Enable rich logging by default
> [tiny] Enable rich logging by default

- configs/projects/judges/doc_qa/completeness.yaml
- configs/projects/judges/doc_qa/groundedness.yaml
- configs/projects/judges/doc_qa/relevance.yaml
- configs/projects/judges/generic/format_compliance.yaml
- configs/projects/judges/generic/instruction_following.yaml
- configs/projects/judges/generic/safety.yaml
- configs/projects/judges/generic/topic_adherence.yaml
- configs/projects/judges/generic/truthfulness.yaml
Lower judgment inference temperatures to 0 
Towards OPE-1327
> Judge API V2 | Lower inference temperatures

- docs/index.md
- docs/user_guides/quantization.md
> [docs] Add quantization docs to index, minor cleanups

- notebooks/Oumi - Bulk Inference of LLM APIs.ipynb
> Add notebook for bulk inference

- notebooks/Oumi - Quantization Tutorial.ipynb
- [tiny] remove deprecated param from quantization notebook
> [tiny] remove deprecated param from quantization notebook

- notebooks/Oumi - Quantization Tutorial.ipynb
- src/oumi/quantize/awq_quantizer.py
- src/oumi/quantize/constants.py
- src/oumi/utils/device_utils.py
Remove requirements for output_format="pytorch" and update the error catching for `NVML_ERROR_NOT_SUPPORTED` as `NVMLError_NotSupported` is not a valid attribute of `pynvml`.
Fixes OPE-1472
> Fix quantization notebook related errors

- .github/workflows/install_test.yaml
- pyproject.toml
> Temporarily disable python 3.13 support to unblock pip release

- configs/recipes/gpt_oss/README.md
- configs/recipes/gpt_oss/inference/120b_together_infer.yaml
Remote inference via Together AI
Towards #1906
> Add gpt-os-120b Together AI inference config

- src/oumi/core/synthesis/dataset_planner.py
- tests/unit/core/synthesis/test_dataset_planner.py
> Update dataset planner to use dependency injection

- src/oumi/core/synthesis/document_ingestion.py
- tests/unit/core/synthesis/test_document_ingestion.py
> Modify document ingestion to read bytes

- README.md
Add the August webinar link to our README.
> Add august webinar to the readme.

- README.md
> Update README.md to highlight `gpt-oss` support

- .vscode/launch.json
- configs/recipes/gpt2/pretraining/macos_train.yaml
- configs/recipes/phi3/dpo/macos_train.yaml
- configs/recipes/phi3/sft/lora_macos_train.yaml
- docs/faq/troubleshooting.md
> [tiny] Rename mac to macos in config names

- src/oumi/core/configs/params/synthesis_params.py
- src/oumi/core/synthesis/attribute_formatter.py
- src/oumi/core/synthesis/dataset_planner.py
- tests/unit/core/configs/params/test_synthesis_params.py
- tests/unit/core/synthesis/test_attribute_formatter.py
- tests/unit/core/synthesis/test_attribute_synthesizer.py
- tests/unit/core/synthesis/test_data_synthesizer.py
- tests/unit/core/synthesis/test_dataset_planner.py
- Renamed PermutableAttribute to SampledAttribute
- Reworked SampledAttribute formatting
Previous:
{id} ({id.description}) - {id.value} ({id.value.description})
New:
{id.parent} ({id.parent.description}) - {id} ({id.description})
(Swaps concept of "value" with "Parent", as more likely to utilize the value itself, which also aligns more with how non-sampled attributes are specified in configs, making only the "parent" part of the attribute the special case)
> Update synthesis with usability feedback

- src/oumi/core/analyze/dataset_analyzer.py
- tests/unit/core/analyze/test_dataset_analyzer.py
extract conversation_turns from conversation_level_summary to top level
> extract conversation_turns from conversation_level_summary to top level

- tests/integration/datasets/test_sft_vision_datasets_load_datasets.py
Adding an `__init__.py` in the `datasets` directory caused a naming conflict with the `datasets` pypi package. Removing it.
N/A
> Quick fix for our GPU tests
