oumi-ai/oumi

notebooks/Oumi - Deploying a Job.ipynb
notebooks/Oumi - Distill a Large Model.ipynb
notebooks/Oumi - Finetuning Tutorial.ipynb
notebooks/Oumi - Launching Jobs on Custom Clusters.ipynb
notebooks/Oumi - Training CNN on Custom Dataset.ipynb
notebooks/Oumi - Using vLLM Engine for Inference.ipynb
notebooks/Oumi - Vision Language Models.ipynb

-  Update installation instructions for colab
Closes OPE-882

[notebooks] Update installation instructions for colab

---

configs/recipes/vision/qwen2_vl_2b/sft/train.yaml
configs/recipes/vision/smolvlm/sft/gcp_job.yaml
configs/recipes/vision/smolvlm/sft/train.yaml

-- Remove unnecessary dataset limits for SmolVLM and Qwen2-VL
-- SmolVLM: `--exclude "onnx/*`
-- Tested on GCP
-- The changes are similar to https://github.com/oumi-ai/oumi/pull/1287 and https://github.com/oumi-ai/oumi/pull/1306
Fixes OPE-951

Tune VLM configs for  SmolVLM and Qwen2-VL

---

src/oumi/core/configs/params/data_params.py
tests/unit/core/configs/params/test_data_params.py

-- This may lead to obscure Python kwarg resolution error (function call with duplicate keyed arguments). Better to block it from the start.
Fixes OPE-916

Disallow using `DatasetParams` field names as keys in `DatasetParams.dataset_kwargs`

---

configs/recipes/vision/llama3_2_vision/sft/11b_full/gcp_job.yaml
configs/recipes/vision/llama3_2_vision/sft/11b_full/train.yaml
configs/recipes/vision/llama3_2_vision/sft/11b_lora/gcp_job.yaml
configs/recipes/vision/llama3_2_vision/sft/11b_lora/train.yaml
configs/recipes/vision/llama3_2_vision/sft/90b_full/gcp_job.yaml
configs/recipes/vision/llama3_2_vision/sft/90b_full/train.yaml
pyproject.toml
scripts/benchmarks/minimal_fsdp_training.py
scripts/benchmarks/minimal_multimodal_training.py
src/oumi/core/trainers/oumi_trainer.py
src/oumi/models/layers/ring_attention.py
tests/integration/models/test_integration_cnn_classifier.py
tests/integration/train/test_custom_models.py
tests/unit/core/trainers/test_oumi_trainer.py

Llama vision attention is still broken. Nikolai determined it occurs when gradient checkpointing is enabled, and filed an issue here: https://github.com/huggingface/transformers/issues/36040.
Since this can be worked around, and only affects one family of models, we still want to upgrade the version. 4.45 is 4 months old, and we need newer transformers versions to support new vision models.
We attempted this previously, and reverted it in #1111 due to the same issue.
Main code changes required are:
- Rename `tokenizer` to `processing_class`
- Update some attention class names due to HF Transformers' attention refactor https://github.com/huggingface/transformers/pull/35235
Fixes OPE-738, OPE-875
Towards OPE-1018

Update transformers version to 4.48

---

pyproject.toml

The last stable version of omegaconf is two years old and is causing dependency issues with azure. It's in maintenance mode, and there's no certainty on when the next stable version will release, so we'll upgrade to the dev version for now (which is a year old).
Tested that `pip install '.[azure]'` works in a fresh conda env, and that a simple training job works.
Fixes #1377

Upgrade omegaconf to 2.4.0dev3

---

README.md

We don't have quickstart job configs for the other cloud providers. Instead of adding them, I opted to override the cloud value instead:
- The configs would have high overlap
- This demonstrates how simple it is to switch clouds from the CLI
- Takes up less real estate on the README page

[tiny] Remove references to missing job configs in README

---

notebooks/Oumi - Vision Language Models.ipynb
scripts/datasets/save_conversations.py
src/oumi/core/types/conversation.py
tests/unit/core/types/test_conversation.py

-- Add flags to split multi-turn conversations into N single-turn conversations
-- Modify `Conversation.filter_messages()` method to accept user-defined  predicate.

Update `save_conversations` tool

---

src/oumi/utils/torch_utils.py
tests/unit/utils/test_torch_utils.py

-- The function pads input tensors to maximum size in each dimension, then stacks them
-- This is similar to `pad_sequences()` except it can pad to more than one dimension, which is needed e.g., for `cross_attention_mask` which has two variable dimensions: `seq_len`, `num_images` for multi-image multimodal examples
-- The integration of this new function into data pipeline is coming in a separate PR.
-- Minor error logging improvements in padding utils

Create `pad_to_max_dim_and_stack()` function in torch_utils

---

.gitignore
src/oumi/core/configs/params/training_params.py

Passed in several new parameters to HF Trainer. Added new behavior to use_deterministic to make it more deterministic in distributed training environments. Resolves OPE-891.

Additional HF trainer parameters for config

---

tests/unit/datasets/test_tulu3_sft_mixture.py

I noticed that occasional unit test runs were timing out. The root cause is that the tulu3 dataset loads real data in its initializer. However, the test only tests instance methods that are stateless.
I've mocked out the `__init__` method to make these tests hermetic.
N/A

Make the tulu3 unit tests hermetic.

---

docs/user_guides/launch/launch.md
src/oumi/core/configs/job_config.py
src/oumi/launcher/clients/sky_client.py
tests/unit/launcher/clients/test_sky_client.py

Two bug fixes were made to enable running on RunPod and Lambda:
1. Change the default value of `disk_tier` from "medium" to None. This is because only AWS, Azure, GCP, and OCI support low/medium/high disk tiers, and the rest only support "best'.
- This should still default to medium in SkyPilot, for clouds that support it I assume: https://github.com/skypilot-org/skypilot/blob/8ee8230c5519d42d0ac8fb9203f01a8950377f92/sky/resources.py#L140.
- IMO we can also set the default value to "best", as disk cost is likely minimal compared to GPU cost, and using higher tiers makes disk I/O less likely to bottleneck.
2. Only set autostop if the cloud supports it. RunPod and Lambda both don't support it. Referencing this code: https://github.com/skypilot-org/skypilot/blob/aa3c387f04fbdd4468751b7d66fcb3 …

Fix Oumi launcher to be able to run on RunPod and Lambda

---

src/oumi/core/registry/registry.py
tests/unit/core/test_registry.py

Previously we were loading external deps using an arbitrary module name. This had the benefit of preventing of preventing module conflicts, but the downside of python not being able to recognize when a module was already imported.
For custom models, this led to a scenario where a module would be imported twice, causing python to try to register the model 2x with Oumi. This is currently a fatal error, and crashes out.
The new change temporarily appends the directory of the python module to the user's sys path (this is reset when the python session ends). This means local references to the module will now resolve properly. The main downside here is that users must be careful that their *.py files don't conflict with any other packages they need (like `pathlib`, `time`, etc).
Fixes #1475
At …

Fix local models to not break the registry.

---

pyproject.toml

This is needed for the GRPO trainer., which was added in 0.14.0. We'd ideally like to upgrade to the latest, 0.15.1, which seems to have a decent number of updates to GRPOTrainer. However, 0.15.0 changes the SFTTrainer to only accept HF datasets or a ConstantLengthDataset. Our custom PyTorch datasets thus no longer work, and additional time is needed to do a migration to fix this.
Release history:
- 0.13.0: 12/16/24
- 0.14.0: 1/29/25
- 0.15.0: 2/13/25
- 0.15.1: 2/18/25
TRL release notes: https://github.com/huggingface/trl/releases. At a glance, there doesn't seem to be any other breaking changes for this version update.
Tested by running `configs/recipes/llama3_2/sft/3b_lora/gcp_job.yaml` and `configs/recipes/vision/llama3_2_vision/sft/11b_lora/gcp_job.yaml` as a sanity check.
Towards …

[tiny]Update trl to 0.14

---

src/oumi/cli/infer.py
tests/unit/cli/test_cli_infer.py

This is a Quality of Life change for the CLI. If the user doesn't specify interactive inference AND doesn't specify an input path, we'll default to interactive inference.
Additionally, we'll always prevent interactive inference if the user specifies an input file. This is in preparation for removing this flag. We should instead use the presence of the `input_file` as an indicator for whether or not we run interactive inference.

Update oumi infer to fall back to interactive mode if no input path is specified.

---

.vscode/launch.json
src/oumi/inference/vllm_inference_engine.py
src/oumi/utils/hf_utils.py
tests/unit/inference/test_vllm_inference_engine.py
tests/unit/utils/test_hf_utils.py

-- Use HF-supplied chat templates for VLM-s in vLLM in-process inference engine. The change will be reverted once we have a more general solution (requires more effort)
-- Solves the error for Llava and Qwen. Not effective for LLAVA (no chat template) and Phi3 (text-only template)
-- Create new helper function `get_hf_chat_template()`
Towards OPE-1090

Temporary fix for chat template issue with multimodal inference w/ in-process vLLM engine

---

src/oumi/inference/remote_inference_engine.py
tests/unit/inference/test_remote_inference_engine.py

During inference, `oumi infer` would fail if the user specified any remote_params via the CLI for wrapper engines (engines that inherit from the RemoteInferenceEngine). This is because the merged config specified at inference time had `None` values for required API fields.
Updated the infer method to gracefully fallback to previous values if `None` values are detected at runtime.
N/A

Fix a bug where overriding remote_params fails via the CLI (oumi infer)

---

.vscode/launch.json
configs/recipes/smollm/evaluation/135m/quickstart_alpaca_v2_eval.yaml

Limiting the AlpacaEval number of samples for quickstart

---

configs/examples/bulk_inference/gcp_job.yaml
notebooks/Oumi - Vision Language Models.ipynb
pyproject.toml

-- Also run manual tests with: `oumi infer -i -c configs/recipes/llama3_2/inference/1b_vllm_infer.yaml` , `oumi infer -i -c configs/recipes/vision/llava_7b/inference/vllm_infer.yaml --image=<...>`
Fixes OPE-1106

vLLM version increment

---

configs/examples/grpo_tldr/gcp_job.yaml

-- Check if global batch size is divisible by num_generations . Otherwise, training may fail (depending on `trl` version)
Fixes OPE-993

Update sample GRPO script to validate num_generations

---

configs/projects/aya/evaluation/eval.yaml
configs/recipes/deepseek_r1/evaluation/distill_llama_70b/eval.yaml
configs/recipes/deepseek_r1/evaluation/distill_llama_8b/eval.yaml
configs/recipes/deepseek_r1/evaluation/distill_qwen_1_5b/eval.yaml
configs/recipes/deepseek_r1/evaluation/distill_qwen_32b/eval.yaml
configs/recipes/gpt2/evaluation/async_eval.yaml
configs/recipes/llama3_1/evaluation/70b_eval.yaml
configs/recipes/llama3_1/evaluation/8b_eval.yaml
configs/recipes/llama3_2/evaluation/1b_eval.yaml
configs/recipes/llama3_2/evaluation/3b_eval.yaml
configs/recipes/llama3_3/evaluation/70b_eval.yaml
configs/recipes/phi3/evaluation/eval.yaml
configs/recipes/qwq/evaluation/eval.yaml
configs/recipes/smollm/evaluation/135m/eval.yaml
configs/recipes/smollm/evaluation/135m/leaderboards/huggingface_leaderboard_v1_eval.yaml
configs/recipes/smollm/evaluation/135m/leaderboards/huggingface_leaderboard_v2_eval.yaml
configs/recipes/smollm/evaluation/135m/quickstart_alpaca_v2_eval.yaml
configs/recipes/smollm/evaluation/135m/quickstart_eval.yaml
configs/recipes/vision/llama3_2_vision/evaluation/11b_eval.yaml
configs/recipes/vision/qwen2_vl_2b/evaluation/eval.yaml
src/experimental/configs/projects/zephyr/evaluation/eval.yaml
src/oumi/core/configs/params/evaluation_params.py
tests/unit/core/evaluation/test_save_utils.py

`evaluation_platform` was renamed to `evaluation_backend` throughout our codebase in #1484. This causes an error in all our eval configs at main, which use the YAML config from HEAD but the Oumi package from PyPi (which hasn't picked up this rename).
This PR:
- Renames `evaluation_backend` back to `evaluation_platform` to fix the breakage
- Updates `EvaluationTaskParams` so that `evaluation_backend` is not a required field. This will cause a breakage on main, as our configs don't provide this value anymore. Also updates post_init logic in this class to expect one of the two fields to be populated, not none or both.
- Fixes a test
After the next PyPI push, we can revert this change.
Tested that there's no errors both when using the PyPI package and using source.

Switch eval yaml configs to use evaluation_platform

---

src/oumi/core/evaluation/evaluator.py
tests/unit/core/evaluation/test_evaluator.py

Custom evals: Adding support for `eval_kwargs`

[Evaluations] Custom evals: Adding support for `eval_kwargs`

---

notebooks/Oumi - Build your own Custom Evaluation (Hallucination Classifier).ipynb
src/oumi/core/evaluation/evaluator.py
src/oumi/core/registry/registry.py
tests/unit/core/evaluation/test_evaluator.py
tests/unit/core/test_registry.py

1. Removing restrictions: Making the arguments `task_params` and `config` of the custom evaluation function optional. If users choose to define them, these will be populated but our Evaluator. If they don't need these, we should not make this function unnecessarily more complex by forcing them to define these.
2. Adding error checking for keyword arguments and providing better explanations when custom evals fail. Specifically: 
- Ensuring that user-provided keyword arguments, which are passed into method `Evaluator.evaluate` do NOT contain any reserved keys.
- Ensuring that user-provided keyword arguments match the expected input parameters of the custom evaluation function. If not, display to the user which specific arguments are unrecognized (provided by the user, but not known to the …

[Evaluation][Custom] Removing restrictions and better error checking

---

src/oumi/cli/env.py

`device_count()` has no type annotation and can return a number, which typer cannot parse. This CL casts erroneous values to strings before printing.
N/A

Fix printing errors in oumi env for non-string values.

---

src/oumi/core/datasets/base_grpo_dataset.py

The default behavior of this function parallels the default behavior for `transform()`. This fixes the broken GRPO TLDR example.
Fixes OPE-1176

[GRPO] Implement `transform_conversation()` in `BaseExperimentalGrpoDataset`

---

src/oumi/cli/env.py

This PR adds `mlflow` to the list of core packages shown when running the `oumi env` command. This change allows users to see the installed version of `mlflow` as part of the environment report, which is helpful for debugging.
#1600 
@oumi-ai/oumi-staff

feat (env): include mlflow in displayed dependencies

---

configs/examples/bulk_inference/gcp_job.yaml
configs/examples/grpo_tldr/gcp_job.yaml
configs/examples/letter_counting/evaluation/eval.yaml
configs/examples/letter_counting/evaluation/gcp_job.yaml
configs/examples/letter_counting/grpo/gcp_job.yaml
configs/recipes/llama3_1/inference/8b_rvllm_infer.yaml
configs/recipes/llama3_2/inference/1b_vllm_infer.yaml
configs/recipes/llama3_2/inference/3b_vllm_infer.yaml
configs/recipes/llama3_3/inference/70b_vllm_infer.yaml
configs/recipes/vision/llama3_2_vision/inference/11b_rvllm_infer.yaml
configs/recipes/vision/llama3_2_vision/inference/11b_vllm_infer.yaml
configs/recipes/vision/llava_7b/inference/vllm_infer.yaml
configs/recipes/vision/phi3/inference/vllm_infer.yaml
configs/recipes/vision/phi4/inference/vllm_infer.yaml
configs/recipes/vision/qwen2_5_vl_3b/inference/vllm_infer.yaml
configs/recipes/vision/qwen2_vl_2b/inference/vllm_infer.yaml
docs/user_guides/infer/inference_engines.md
notebooks/Oumi - Build your own Custom Evaluation (Hallucination Classifier).ipynb
notebooks/Oumi - Distill a Large Model.ipynb
notebooks/Oumi - Finetuning Tutorial.ipynb
notebooks/Oumi - MiniMath-R1-1.5B.ipynb
notebooks/Oumi - Using vLLM Engine for Inference.ipynb
notebooks/Oumi - Vision Language Models.ipynb
pyproject.toml
src/oumi/launcher/clusters/polaris_cluster.py
tests/unit/launcher/clusters/test_polaris_cluster.py

Currently, running `pip install oumi vlm` errors, because the latest version of vllm uses a later version of pytorch than what oumi uses. Even if we fix this problem now, it's not sustainable to keep changing our vllm version requirements throughout our codebase instead of in one central place. Since we basically only install vllm whenever we're installing `oumi[gpu]`, i'm moving it back into this target. It seems I initially moved it out because vllm doesn't *require* a gpu to run: https://github.com/oumi-ai/oumi/pull/894/files. However, if you own a GPU, there's a good chance you may want to install vllm, so I think it still makes sense to include it there. I haven't seen a need to install vllm on a non-GPU machine yet.

Add `vllm` to `gpu` optional dependencies

---

configs/projects/halloumi/halloumi_inference_notebook.ipynb
pyproject.toml

- Install oumi from source, because this colab uses the newly added `to_str()` fn
- Add a cell suggesting to install vllm
- Limit model max length or else it surpasses kv cache size

[HallOumi] Update inference notebook

---

configs/recipes/vision/qwen2_5_vl_3b/README.md
configs/recipes/vision/qwen2_5_vl_3b/inference/infer.yaml
configs/recipes/vision/qwen2_5_vl_3b/inference/vllm_infer.yaml
configs/recipes/vision/qwen2_5_vl_3b/sft/full/train.yaml
configs/recipes/vision/qwen2_5_vl_3b/sft/lora/train.yaml
pyproject.toml
tests/e2e/test_eval_e2e.py
tests/unit/builders/test_models.py

This is needed for the new Llama 4 models.
After this is pushed to PyPi, we can remove the transformers import line in Llama 4 configs.
Additional changes:
- Remove stale comments in `configs/recipes/vision/qwen2_5_vl_3b` about transformer version
- Fix eval E2E test (make the Llama 8B model a simple evaluate)
- Update `test_models.py` now that our transformers version is updated
Tested by running `tests/scripts/launch_tests.sh`. I didn't observe any errors mentioned by #/1577.
Fixes #1619

Update transformers to 4.51.0

---

src/oumi/launcher/clients/sky_client.py
src/oumi/launcher/clouds/sky_cloud.py
src/oumi/launcher/clusters/sky_cluster.py
tests/unit/launcher/clouds/test_sky_cloud.py
tests/unit/launcher/test_launcher.py

This change updates all skypilot entry points to lazy load the `sky` library. This prevents DB locking that can occur when using skypilot in a multithreaded environment.
I also added a test to ensure that `sky` is not loaded when importing the `oumi.launcher` module.
Fixes #1605

Lazy load skypilot

---

src/oumi/__init__.py
src/oumi/train.py

This pull request includes several changes to the `train` function and related methods in the `oumi` module to support additional model and trainer keyword arguments. The motivation was to allow passing non-serializable keyword arguments into the trainer class (and the model class). The most important changes are as follows:
* Modified the `train` function in `src/oumi/__init__.py` to accept `additional_model_kwargs` and `additional_trainer_kwargs` parameters and pass them to the `oumi.train.train` function.
* Updated the `_create_optional_training_kwargs` function to accept an `additional_trainer_kwargs` parameter and include it in the returned dictionary. [[1]](diffhunk://#diff-883bb6b1dff705e291235aa01c36f1b4d1a80d1907c27b30bcf299f7c63972d2R192) …

Add additional_model_kwargs and additional_trainer_kwargs to train function

---

configs/examples/berry_bench/evaluation/gcp_job.yaml
configs/examples/letter_counting/evaluation/gcp_job.yaml
configs/projects/halloumi/halloumi_inference_notebook.ipynb
configs/recipes/llama4/inference/scout_instruct_vllm_infer.yaml
notebooks/Oumi - Train a Letter Counting Model using GRPO.ipynb

With oumi 0.1.12 published on PyPI today, vllm is now included in the [gpu] optional dependencies. Tested on GCP.

[tiny] Remove vllm install commands

---

configs/recipes/vision/phi4/sft/lora/train.yaml
scripts/benchmarks/minimal_multimodal_training.py
src/oumi/builders/collators.py
src/oumi/core/collators/vision_language_sft_collator.py
src/oumi/core/configs/training_config.py
src/oumi/core/datasets/vision_language_dataset.py
src/oumi/core/feature_generators/vision_language_conversation_feature_generator.py
tests/unit/core/configs/test_training_config.py

-- Plumbing to populate `processor_kwargs` in VL SFT collator and in VL SFT dataset
-- Copy `model.processor_kwargs` to `dataset_kwargs` if the same processor name is used in both, and if `processor_kwargs`   isn't already configured there.
Towards OPE-1185

Support for custom `processor args`: misc improvements

---

tests/e2e/test_train_e2e.py
tests/scripts/lambda_e2e_tests_job.yaml
tests/scripts/launch_tests.sh

- Swapped e2e tests to run on Lambda
- Swapped A100-80GB:4 with H100:4 since the former isn't available in Lambda
- Fixed a broken qwen e2e test, since the config `configs/recipes/vision/qwen2_vl_2b/sft/train.yaml` was moved to `configs/recipes/vision/qwen2_vl_2b/sft/full/train.yaml`.
- I updated the test to run multi-GPU since that's how the config is running it; wasn't sure if there's a specific reason it was set to be a 24GB 1 GPU test before.
- Added a test for the parallel `configs/recipes/vision/qwen2_vl_2b/sft/lora/train.yaml` config.
I've tested that "A100:1" and "H100:4"GPU tests work. I've been unable to schedule "A100:4" tests work since there hasn't been enough capacity on Lambda, but the tests are covered by the H100:4 tests.

Update e2e tests to run on lambda

---

README.md
configs/recipes/qwen3/README.md
configs/recipes/qwen3/evaluation/32b_eval.yaml
configs/recipes/qwen3/evaluation/32b_gcp_job.yaml
configs/recipes/qwen3/inference/32b_infer.yaml
configs/recipes/qwen3/sft/32b_lora/gcp_job.yaml
configs/recipes/qwen3/sft/32b_lora/train.yaml
src/oumi/cli/alias.py
src/oumi/inference/native_text_inference_engine.py

Add configs for Qwen3 32B model for LoRA, eval, and inference, derived from QwQ configs. Also updated the README and aliases.
Note that the model does thinking by default, and a future PR will extend support for non-thinking models. More configs will be added in future PRs as well.
Tested that all these configs work.
Towards OPE-1209

Add Qwen3 32B configs

---

src/oumi/core/configs/params/training_params.py
src/oumi/core/trainers/verl_grpo_trainer.py
src/oumi/core/trainers/verl_trainer_config.yaml
src/oumi/train.py
tests/unit/core/trainers/test_verl_grpo_trainer.py

- Add a `verl_config_overrides` field in TrainingParams to allow setting any verl config value. This is similar to what `trainer_kwargs` does for HF/TRL trainers, and gives users flexibility to pass in fields we don't have in Oumi configs.
- Replace `TrainingParams` with `TrainingConfig` in verl trainer initialization since values in the latter are needed for verl.
- Populate verl config from some Oumi config fields and user-provided overrides.
Future work
- Add more Oumi -> verl config field converters. This PR only adds a few, but adding more is time-consuming. There are 200 verl config values, and I need to read into the verl codebase for many as similarly-named params in Oumi/trl/verl are not the same. For example, `max_prompt_length` in Oumi/trl will truncate prompts longer than that …

[verl] Populate verl config from Oumi config

---

configs/examples/grpo_verl_countdown/gcp_job.yaml
configs/examples/grpo_verl_countdown/train.yaml
pyproject.toml
src/oumi/core/trainers/verl_grpo_trainer.py
src/oumi/core/trainers/verl_trainer_config.yaml

- Add job and train configs for Countdown task using verl GRPO. The majority of the params are passed in via the `verl_config_overrides` field.
- Changed version of default verl config to the one from version 0.3.0post1, as opposed to the latest one.
- Always add a reference policy, since KL loss is always enabled for GRPO.
Towards OPE-1192

Add verl GRPO Countdown configs

---

configs/examples/grpo_verl_countdown/gcp_job.yaml
configs/examples/grpo_verl_countdown/train.yaml
src/oumi/core/trainers/verl_grpo_trainer.py
src/oumi/core/trainers/verl_trainer_config.yaml

Update configs to match the first experiment in https://github.com/matthewyryang/countdown-curriculum/blob/main/scripts/grpo/3_6_curriculum/run_difficulty.sh.
Also updated verl trainer to resolve variable interpolations in config.
Tested on GCP, and verified that our resulting config is equivalent to the one in the original experiment, aside from differences due to differing verl versions (we use v0.3.0.post1, the original uses a later commit from April 8).
The following is the delta between the configs. "verl" means the original experiment, and "Oumi" means the verl config generated by the Oumi config in this PR.
```
actor_rollout_ref.actor.clip_ratio_c: 3.0
actor_rollout_ref.actor.clip_ratio_high: 0.2
actor_rollout_ref.actor.clip_ratio_low: 0.2
actor_rollout_ref.actor.loss_agg_mode: …
```

Update verl GRPO countdown configs

---

src/oumi/core/evaluation/utils/save_utils.py

This PR adds functionality to serialize and save the `EvaluationConfig` used during `oumi evaluate` into the output directory as a YAML file (`evaluation_config.yaml`). This ensures configuration details are stored with evaluation outputs, improving reproducibility and experiment transparency.
**Key changes:**
- Added `_convert_to_serializable` utility to handle serialization of complex types (Enums, nested custom classes), addressing limitations in default YAML serialization.
- Integrated config saving into `save_evaluation_output` pipeline.
- Verified output directory contains complete `evaluation_config.yaml`.
Fixes #1546 ([https://github.com/oumi-ai/oumi/issues/1546](https://github.com/oumi-ai/oumi/issues/1546))
- wizeng23: [William Zeng](https://github.com/wizeng23)

[Feature] Save evaluation config as YAML in output_dir #1546

---

.vscode/launch.json
scripts/frontier/launcher.sh

-- `-n` is the number of MPI tasks. Currently we launch 1 task per node i.e., `-N` and `-n` should be equal
Towards OPE-1280

Frontier: Fix -n param in launcher script

---

docs/user_guides/train/configuration.md

To get Falcon-H1 model running with the `state-spaces/mamba` and `Dao-AILab/causal-conv1d` libraries, I had to add an additional `bitsandbytes` option to avoid quantizing one of the parameter matrices. This adds documentation for that.

Added doc for new QLoRA param

---

configs/examples/grpo_verl_countdown/gcp_job.yaml
configs/examples/grpo_verl_countdown/train.yaml
configs/examples/grpo_verl_geometry3k/gcp_job.yaml
docs/user_guides/train/training_methods.md
src/oumi/core/configs/params/training_params.py
src/oumi/core/trainers/base_trainer.py
src/oumi/core/trainers/verl_grpo_trainer.py
src/oumi/train.py

- For verl trainer, don't run our logic to find latest checkpoint. Verl will handle this.
- Remove resume_from_checkpoint fn for train() function of verl trainer. We instead set it in the class initialization.
Towards OPE-1260

[verl] Support resuming from checkpoint

---

src/oumi/core/configs/training_config.py
src/oumi/core/trainers/oumi_trainer.py
tests/e2e/test_train_e2e.py

This parameter for SFTConfig is now deprecated. This PR also adds a new test case to integration test cases so that a Liger kernel model is covered.
Fixes OPE-1117

[tiny] Remove `use_liger` argument

---

src/oumi/inference/adaptive_semaphore.py
tests/unit/inference/test_adaptive_semaphore.py

Bounded Semaphores are a lock mechanism allowing a finite amount of "permits" to allow so many "waiters" to access a given resource.
Traditionally, bounded semaphores are a fixed size - once initialized, they keep that capacity.
This PR introduced an Adaptive Semaphore - one which can change its size allocation. For size decreases, nothing special really happens - the existing permits stay valid, but no new permits are granted.
For size increases, the semaphore will immediately grant <delta> waiters access to the resource.
Towards OPE-1307

Add adaptive semaphore to enable future adaptive throughput scenarios

---

src/oumi/core/synthesis/planner.py
tests/unit/core/synthesis/test_planner.py

Integrates document ingestion into the dataset planning process, allowing users to specify attributes in their dataset plan which will be filled with documents and/or document segments, which can then be usable during generation.
Fixes OPE-1297

Add support for document ingestion during data synthesis

---

tests/e2e/test_train_e2e.py

One of the integration tests keeps failing since torch 2.6.0 upgrade. We are going to skip this test (test_train_multimodal_fsdp_4gpu_80gb[train_mm_llama3_2_vision_11b_full]) for now. 
Towards OPE-1329
sky logs oumi-ryanarman-e2e-tests-a100-80gb-4-nonspot:
sky logs oumi-ryanarman-e2e-tests-a100-1-nonspot:
sky logs oumi-ryanarman-e2e-tests-a100-4-nonspot:

Fix integration tests

---

pyproject.toml

See attached Linear issue for details. tl;dr installing oumi with uv often won't work because it is stricter than pip and won't download prerelease packages (i.e. omegaconf) with our current version specifications. Pinning an exact omegaconf version should fix this.
Fixes OPE-1476

[tiny] Pin exact omegaconf version

---

src/oumi/cli/cli_utils.py
src/oumi/cli/main.py

We want to make users more aware that when they run into any types of issues they should open an issue. This PR appends a pre-populated Github issue link after any type of failure occurs for the user to optionally open if they feel it should be tracked by the team.
Example: `oumi launch up -c configs/examples/grpo_verl_countdown/gcp_job.yaml --cluster grpo-verl-countdown`
**BEFORE CHANGES**
**AFTER CHANGERS**
**LONGER ERROR EXAMPLE**
NOTE: For any jobs used with the launcher, rich console logs that leverage links won't work. Instead a check is made and if its a remote job we just display the template for the user to use instead of populating any fields

Add Pre-Populated GitHub Issue Link On Failures

---

docs/user_guides/launch/custom_cluster.md
notebooks/Oumi - Launching Jobs on Custom Clusters.ipynb
src/oumi/core/launcher/__init__.py
src/oumi/core/launcher/base_cluster.py
src/oumi/launcher/clients/local_client.py
src/oumi/launcher/clients/polaris_client.py
src/oumi/launcher/clients/sky_client.py
src/oumi/launcher/clients/slurm_client.py
src/oumi/launcher/clusters/sky_cluster.py
tests/unit/cli/test_cli_launch.py
tests/unit/launcher/clients/data/qstat.txt
tests/unit/launcher/clients/test_local_client.py
tests/unit/launcher/clients/test_polaris_client.py
tests/unit/launcher/clients/test_sky_client.py
tests/unit/launcher/clients/test_slurm_client.py
tests/unit/launcher/clouds/test_frontier_cloud.py
tests/unit/launcher/clouds/test_local_cloud.py
tests/unit/launcher/clouds/test_polaris_cloud.py
tests/unit/launcher/clouds/test_sky_cloud.py
tests/unit/launcher/clouds/test_slurm_cloud.py
tests/unit/launcher/clusters/test_frontier_cluster.py
tests/unit/launcher/clusters/test_local_cluster.py
tests/unit/launcher/clusters/test_polaris_cluster.py
tests/unit/launcher/clusters/test_sky_cluster.py
tests/unit/launcher/clusters/test_slurm_cluster.py
tests/unit/launcher/test_launcher.py

Previously the oumi launcher only exposed a `done` enum, as well as a string for status parsing. This PR adds an enum `state` to easily check if a job is `pending`, `failed`, `succeeded`, or `cancelled`.

Add a parsable enum state field to the launcher to convey job status

---

.github/workflows/doctests.yaml
.github/workflows/gpu_install_test.yaml
.github/workflows/gpu_tests.yaml
.github/workflows/install_test.yaml
.github/workflows/pretest.yaml
.github/workflows/release_docker.yaml
.github/workflows/release_pypi.yaml

Currently, our test workflows are run whenever a PR is opened, synchronize, or reopened. This is eating into our quota. This PR instead has those tests run in a merge queue when the PR is submitted (with the exception of pretest.yaml, which we keep running for PR updates). The user is still able to run tests manually before the PR is submitted with the `workflow_dispatch` hook.
Documentation: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue
https://docs.github.com/en/actions/reference/workflows-and-actions/events-that-trigger-workflows#pull_request
Fixes OPE-1512

Run GitHub workflows in merge queue instead of on PR events

---

tests/integration/datasets/test_sft_vision_datasets_load_datasets.py

Fixes an error with name conflicts for tests:
```
(oumi-e2e-tests, pid=4177) ==================================== ERRORS ====================================
(oumi-e2e-tests, pid=4177) __________________ ERROR collecting tests/unit/test_train.py ___________________
(oumi-e2e-tests, pid=4177) import file mismatch:
(oumi-e2e-tests, pid=4177) imported module 'test_train' has this __file__ attribute:
(oumi-e2e-tests, pid=4177)   /home/gcpuser/sky_workdir/tests/integration/train/test_train.py
(oumi-e2e-tests, pid=4177) which is not the same as the test file we want to collect:
(oumi-e2e-tests, pid=4177)   /home/gcpuser/sky_workdir/tests/unit/test_train.py
(oumi-e2e-tests, pid=4177) HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
(oumi-e2e-tests, …
```

[tiny] Add `__init__.py` to some test dirs

---

tests/scripts/e2e_tests_job.yaml

Add `CUDA_LAUNCH_BLOCKING` to environment vars to improve cuda debugging for intermittent failing jobs
Towards OPE-1565

Add cuda launch blocking arg to e2e tests for debugging
